# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# PostgreSQL external data source configuration (read-only)
postgres_source_config: &postgres_source_config
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_SOURCE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_SOURCE_PORT") { 5432 } %>
  database: <%= ENV.fetch("POSTGRES_SOURCE_DATABASE") { "postgres" } %>
  username: <%= ENV.fetch("POSTGRES_SOURCE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_SOURCE_PASSWORD") { "" } %>
  replica: true
  database_tasks: false

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  postgres_source:
    <<: *postgres_source_config

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  postgres_source:
    <<: *postgres_source_config


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  postgres_source:
    <<: *postgres_source_config
